# Generated by Django 5.0.6 on 2024-07-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_remove_bot_subscription_chats_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=3008388636, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 6, 15, 56, 10, 22071, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
