# Generated by Django 5.0.6 on 2024-07-15 12:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0005_alter_leomatchmodel_user_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leomatchmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.clientbotuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=2152677810, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 12, 45, 3, 36214, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
