# Generated by Django 5.0.6 on 2024-07-15 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_alter_leomatchmodel_user_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=1532926339, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 12, 49, 13, 241605, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
