# Generated by Django 5.0.6 on 2024-07-15 14:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0009_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonclientmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='gptrecordmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='leomatchmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='smsbanmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='smsorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=8282388595, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 14, 2, 36, 556942, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
