# Generated by Django 5.0.6 on 2024-07-15 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0010_alter_anonclientmodel_user_alter_gptrecordmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=9464496243, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 15, 8, 42, 410946, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
