# Generated by Django 5.0.6 on 2024-07-15 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0011_bot_bot_enable_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=8267277821, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='created_at',
            field=models.CharField(default='2024-07-15T16:44:10.042640+00:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 16, 44, 10, 42502, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
