# Generated by Django 5.0.6 on 2024-07-15 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0013_alter_user_uid_alter_usertg_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=8336605703, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 15, 16, 45, 6, 164658, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
