# Generated by Django 4.2.14 on 2024-07-17 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0015_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=2238931605, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 19, 1, 18, 497683, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
