# Generated by Django 5.0.7 on 2024-08-09 12:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0017_alter_user_uid_alter_usertg_last_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=4.0)),
                ('min_amount', models.FloatField(default=60.0)),
                ('admin_channel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.CharField(max_length=255, unique=True)),
                ('channel_id', models.IntegerField(unique=True)),
                ('admins_channel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True)),
                ('inv_id', models.IntegerField()),
                ('add', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='enable_kino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='enable_refs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertg',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertg',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertg',
            name='invited',
            field=models.CharField(default='Никто', max_length=255),
        ),
        migrations.AddField(
            model_name='usertg',
            name='invited_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='usertg',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertg',
            name='refs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertg',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(default=7820355232, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 9, 12, 39, 26, 549504, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('card', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('status', models.CharField(default='ожидание', max_length=255)),
                ('reg_date', models.DateTimeField()),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.usertg', to_field='uid')),
            ],
        ),
    ]
